//! Template generation for CAPABILITY.toml.

use anyhow::Result;
use colored::Colorize;
use std::io::{self, BufRead, Write};
use std::path::Path;

/// Generate a CAPABILITY.toml template.
pub fn generate_capability(name: &str, interactive: bool) -> Result<String> {
    let mut provides = Vec::new();
    let mut requires = Vec::new();
    let mut version = "0.1.0".to_string();
    let mut description = String::new();

    if interactive {
        let stdin = io::stdin();
        let mut stdout = io::stdout();

        print!("{} ", "Version [0.1.0]:".bold());
        stdout.flush()?;
        if let Some(Ok(line)) = stdin.lock().lines().next() {
            let v = line.trim().to_string();
            if !v.is_empty() {
                version = v;
            }
        }

        print!("{} ", "Description:".bold());
        stdout.flush()?;
        if let Some(Ok(line)) = stdin.lock().lines().next() {
            description = line;
        }

        println!("{}", "Provides (one per line, empty line to finish):".bold());
        loop {
            print!("  {} ", "→".green());
            stdout.flush()?;
            if let Some(Ok(line)) = stdin.lock().lines().next() {
                if line.trim().is_empty() {
                    break;
                }
                provides.push(line.trim().to_string());
            }
        }

        println!("{}", "Requires (one per line, empty line to finish):".bold());
        loop {
            print!("  {} ", "→".green());
            stdout.flush()?;
            if let Some(Ok(line)) = stdin.lock().lines().next() {
                if line.trim().is_empty() {
                    break;
                }
                requires.push(line.trim().to_string());
            }
        }
    }

    let mut toml = String::new();
    toml.push_str("# CAPABILITY.toml — SuperInstance Ecosystem\n");
    toml.push_str("# Generated by si-cli\n\n");

    if !description.is_empty() {
        toml.push_str(&format!("description = \"{}\"\n", description));
    }
    toml.push_str(&format!("name = \"{}\"\n", name));
    toml.push_str(&format!("version = \"{}\"\n\n", version));

    if !provides.is_empty() {
        toml.push_str("provides = [\n");
        for p in &provides {
            toml.push_str(&format!("    \"{}\",\n", p));
        }
        toml.push_str("]\n\n");
    } else {
        toml.push_str("provides = []\n\n");
    }

    if !requires.is_empty() {
        toml.push_str("requires = [\n");
        for r in &requires {
            toml.push_str(&format!("    \"{}\",\n", r));
        }
        toml.push_str("]\n");
    } else {
        toml.push_str("requires = []\n");
    }

    Ok(toml)
}

/// Write the generated template to a file.
pub fn write_capability_template(name: &str, output_path: Option<&Path>, interactive: bool) -> Result<()> {
    let content = generate_capability(name, interactive)?;

    let path = match output_path {
        Some(p) => p.to_path_buf(),
        None => std::path::PathBuf::from("CAPABILITY.toml"),
    };

    std::fs::write(&path, &content)?;
    println!(
        "{} Generated {}",
        "✓".green().bold(),
        path.display().to_string().cyan()
    );
    Ok(())
}
